### PR TITLE
Feat/html output format and download json

### PR DESCRIPTION
**Pull request by akramsmahmoud**
1- exclude pnpm-lock files
2- support output format (Json | html) & generate chart in case of html
3- support downloadable json results when open the html page
4- handle error when port already in use
5- some interactive emoji to the logs
6- add MAX_FILES to be showed in the chart
7- when has more than the MAX_FILES, will have button to update the chart with the full data
8- show error message when pass invalid value to the output-format
9- send html when the the output-format is html

### CODE REVIEW

**Comment by Cadienvan** [comment]
I love it! And also, I think this was exacty what @buggyzap had in mind in #5, nice job @akramsmahmoud! I like the low footprint added to implement this feature!

There are only two things I'd change here:
Schermata 2023-05-13 alle 10 17 53
As you can see there are MANY files being touched in the defined time period and it lags a little on my Macbook Pro with M1 Max and also it becomes impossible to look at for a user, so I'd suggest two ways:
1. Write it clearly in the README and suggest to move to a JSON file if analyzing large chunks of data.
2. Provide a "top X files" view and a CTA "view the entire chart" showing the full content, what do you think?

Another thing is related to the filename.. It is being saved as `results-repo.json.json` because both in the event listener and in the `downloadObjectAsJson` we are adding the extension, I'd remove the one in the event listener, do you agree?

**Comment by akramsmahmoud** [comment]
Thanks Mike and Yes I am totally agree with your suggestions! I am going to do them asap!

**Comment by akramsmahmoud** [comment]
New Stuff 
6- add MAX_FILES to be showed in the chart
7- when has more than the MAX_FILES, will have button to update the chart with the full data
8- show error message when pass invalid value to the output-format
9- send html when the the output-format is html

**Comment by buggyzap** [comment]
Good job @akramsmahmoud.

@Cadienvan In my mind was little different at visually level, but at concept level is the same :)

I think there are too much args to remember in specific order or the script fails, what do you thinks about #4? Can you provide a feedback or suggestions?

**Comment by akramsmahmoud** [comment]
Actually maybe me too I have in mind  exactly what's in your mind visually, but I found d3 heatmap a little bit complex and need more time so I decided to start with something simple, following the concept KISS (keep it stupid, simple) 😃

**Pull request merged**
